### ISSUE TITLE
About KlovitClient

### ISSUE THREAD

**Issue by NaysKutzu** [MythicalLTD/MythicalGuard#1]
So if you see this issue, you may know what [KlovitClient](https://github.com/Klovit/KlovitClient) is.

So the owner is just a skid that stole some popular code from the know client called [HolaClient](https://github.com/HolaCLient) and [Heliactyl](https://github.com/openheliactyl/heliactyl).
He is just a skid he steals code from some other GitHub user he does not give any credits, and he demands that is programming it them.
Here is some proof:

They stole HolaClient theme
![img 1](https://i.imgur.com/onw7fRT.png)
![img 2](https://i.imgur.com/kT5bEkS.png)

Next he says he knows JS, but he does not even know how telemetry's work or how to add them!
![img 3](https://i.imgur.com/tW5S7kf.png)
Next he says he can, but he asks for the code for free
![img 4](https://i.imgur.com/Upt786D.png)

The next proof is about the documentations!
He says he wants to code them, but he just asks for the code!
![img 5](https://i.imgur.com/1FmuuMX.png)
![img 6](https://i.imgur.com/G0VYCrT.png)

The next proof is from my dms with him!
He says he got permission from holaclient to use that but as you see in my other proofs the owner does not give permission to him to use that!
![img 7](https://i.imgur.com/o2bydeM.png)

Also, he may abuse some free providers like AWS or just abuse!,
![img 8](https://i.imgur.com/TNli9zZ.png)
![img 10](https://media.discordapp.net/attachments/1168084470608429097/1168121351853309992/image.png?ex=65509cc8&is=653e27c8&hm=84680fcd7c98f040eb2dd4cb251c9d37e7fa86bd80777342085fd2e3103fce1e&=&width=411&height=216)
![img 12](https://media.discordapp.net/attachments/1168084470608429097/1168122163677634643/image.png?ex=65509d8a&is=653e288a&hm=eb769ae9c341a2e29cba9e87355b502e65ecba930e06eca2ea5c21820cfe06c9&=&width=564&height=576)
![img 13](https://media.discordapp.net/attachments/1168084470608429097/1168122371157282857/image.png?ex=65509dbb&is=653e28bb&hm=72e516cf342bbe3efea177e647a2759e6f3486704931024f7334b06f8a103976&=&width=615&height=366)

Here is more proof of him being a skid!
![img 9](https://i.imgur.com/qxGFO7L.png)
Some good proof of him being a programmer!
![img 11](https://media.discordapp.net/attachments/1168084470608429097/1168122042692943922/image.png?ex=65509d6d&is=653e286d&hm=66fadeeb3839209e4c49f7e594f924897820bf6ef09945ef3bcdc053cbb05323&=&width=246&height=114)
![img 14](https://media.discordapp.net/attachments/1168084470608429097/1168122632231723008/image.png?ex=65509dfa&is=653e28fa&hm=ba9670677beeb5715be40d59f8f9f64fc097f91c6ea8e88e2c11100265f42214&=&width=652&height=385)

**Comment by BeastGamer81** [comment]
Any proof of me abusing?
Shut up if you don't have any proof.
I have modified the thme 90% and I have given credits to CR072 and he agreed with me.

**Comment by NaysKutzu** [comment]
> Any proof of me abusing? Shut up if you don't have any proof. I have modified the thme 90% and I have given credits to CR072 and he agreed with me.

I just uploaded every proof that you have no right to use it and that you are a skid

**Comment by Invalidtypo** [comment]
> Any proof of me abusing? Shut up if you don't have any proof. I have modified the theme 90% and I have given credits to CR072 and he agreed with me.

Nope dude, I didn't give you permission to take that file. I just gave you that unfinished theme.

**Comment by NaysKutzu** [comment]
> > Any proof of me abusing? Shut up if you don't have any proof. I have modified the theme 90% and I have given credits to CR072 and he agreed with me.
> 
> Nope dude, I didn't give you permission to take that file. I just gave you that unfinished theme.

Please read what a license means here: https://github.com/HolaClient/HolaClient/blob/latest/LICENSE

**Comment by BeastGamer81** [comment]
> > Any proof of me abusing? Shut up if you don't have any proof. I have modified the theme 90% and I have given credits to CR072 and he agreed with me.
> 
> Nope dude, I didn't give you permission to take that file. I just gave you that unfinished theme.

![image](https://github.com/MythicalLTD/MythicalGuard/assets/57034210/a556c342-3c7f-4327-b51e-07a5ca1cb5af)

**Comment by Nightmaregodss** [comment]
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/85dc4ff0-d76e-4926-8e19-28040ae42deb)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/3ffc47dc-346e-4a7b-9b4e-a67e0dee4e74)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/e1cc8252-2907-4c6a-bff1-cfdd9ea563dd)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/0948b539-b13e-4dcc-967a-afdb090ff340)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/b31a4c53-7311-4a07-9037-bda6cf58fde5)

**Comment by Nightmaregodss** [comment]
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/40fb126d-46e1-415b-8c86-2255ca7b26cb)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/e30ed33d-00a6-4d67-8a67-632518ea8f45)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/248bb11b-f6f6-4bc5-abb4-0a49b93d6748)
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/21c79eba-3e1f-4a92-a709-edbc8ea8a7a2)
Definatly knows js fr

**Comment by Nightmaregodss** [comment]
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/a61d36a1-f42d-45a8-a040-4b486ed4f6b7)

**Comment by Nightmaregodss** [comment]
![image](https://github.com/MythicalLTD/MythicalGuard/assets/81895400/9204fe5e-1b96-4d65-9fbd-901b1b774607)

**Comment by BeastGamer81** [comment]
> ![image](https://user-images.githubusercontent.com/81895400/278863071-9204fe5e-1b96-4d65-9fbd-901b1b774607.png)

"02/09/2022"

**Comment by BeastGamer81** [comment]
> ![image](https://user-images.githubusercontent.com/81895400/278862984-40fb126d-46e1-415b-8c86-2255ca7b26cb.png) ![image](https://user-images.githubusercontent.com/81895400/278862990-e30ed33d-00a6-4d67-8a67-632518ea8f45.png) ![image](https://user-images.githubusercontent.com/81895400/278863005-248bb11b-f6f6-4bc5-abb4-0a49b93d6748.png) ![image](https://user-images.githubusercontent.com/81895400/278863026-21c79eba-3e1f-4a92-a709-edbc8ea8a7a2.png) Definatly knows js fr

I learnt it later dumbo

**Comment by NaysKutzu** [comment]
you just proved how idiot you are?

**Comment by BeastGamer81** [comment]
> you just proved how idiot you are?

Yes.

**Comment by BeastGamer81** [comment]
Just close this, every issue has been resolved.

**Comment by NaysKutzu** [comment]
> Just close this, every issue has been resolved.

Ohh, so you want to hide the fact that you abuse and card and also skid?

Nahhh this stays open!

**Comment by BeastGamer81** [comment]
> > Just close this, every issue has been resolved.
> 
> Ohh, so you want to hide the fact that you abuse and card and also skid?
> 
> Nahhh this stays open!

I don't abuse and card tho. DE1 is from Dribble.fun and Paid-IN1 is from Cubix.host (Web-1 is locally hosted.)

**Comment by BeastGamer81** [comment]
Nothing is skidded yet.

**Comment by NaysKutzu** [comment]
> > > Just close this, every issue has been resolved.
> > 
> > 
> > Ohh, so you want to hide the fact that you abuse and card and also skid?
> > Nahhh this stays open!
> 
> I don't abuse and card tho. DE1 is from Dribble.fun and Paid-IN1 is from Cubix.host (Web-1 is locally hosted.)

What I don't give a Shit this stays open and do not make me rename this to your real life name because then you will not be able to get a job. For what you did, I'm surprised that I did not report you already

**Comment by lordwolfyy** [comment]
> > > Just close this, every issue has been resolved.
> > 
> > 
> > Ohh, so you want to hide the fact that you abuse and card and also skid?
> > Nahhh this stays open!
> 
> I don't abuse and card tho. DE1 is from Dribble.fun and Paid-IN1 is from Cubix.host (Web-1 is locally hosted.)

Cubix.host is one of layers new acquired hosting. + they abuse aws if you look at their dns reccords

**Comment by NaysKutzu** [comment]
> Cubix.host

Ye here is proof 
https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=Cubix.host
https://securitytrails.com/domain/Cubix.host/dns

**Comment by BeastGamer81** [comment]
> > > > Just close this, every issue has been resolved.
> > > 
> > > 
> > > Ohh, so you want to hide the fact that you abuse and card and also skid?
> > > Nahhh this stays open!
> > 
> > 
> > I don't abuse and card tho. DE1 is from Dribble.fun and Paid-IN1 is from Cubix.host (Web-1 is locally hosted.)
> 
> Cubix.host is one of layers new acquired hosting. + they abuse aws if you look at their dns reccords

I don't really know tho, I paid with LTC and doge

**Comment by BeastGamer81** [comment]
> > > > Just close this, every issue has been resolved.
> > > 
> > > 
> > > Ohh, so you want to hide the fact that you abuse and card and also skid?
> > > Nahhh this stays open!
> > 
> > 
> > I don't abuse and card tho. DE1 is from Dribble.fun and Paid-IN1 is from Cubix.host (Web-1 is locally hosted.)
> 
> What I don't give a Shit this stays open and do not make me rename this to your real life name because then you will not be able to get a job. For what you did, I'm surprised that I did not report you already

It's a nice thing that you didn't rename this and There is a [CREDITS.md](https://github.com/Klovit/KlovitClient/blob/main/CREDITS.md) is KlovitClient's repo

**Comment by BeastGamer81** [comment]
Will you close this if I implement some things in KlovitClient by myself like MySQL Integration and stuff? (I did everything by myself but still I have to prove it.)

**Comment by NaysKutzu** [comment]
> Will you close this if I implement some things in KlovitClient by myself like MySQL Integration and stuff? (I did everything by myself but still I have to prove it.)

It is not about that it is just about the things you have done but sure IL close this. But if i find another shit you are going to do this will get reopen ok?

**Comment by BeastGamer81** [comment]
Thanks and uhm can yu tell me how do I make a user friendly docs?

**Comment by NaysKutzu** [comment]
> Thanks and uhm can yu tell me how do I make a user friendly docs?

Use docusaurs
